spring:
  application:
    name: color-publisher
  rabbit:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      function.definition: sendColor;receive
      bindings:
        sendColor-out-0:
          destination: colors
        receive-in-0:
          destination: colors

server:
  port : 8091

colors:
  mapping:
    red: "255,0,0"
    green: "0,255,0"
    blue: "0,0,255"